language: java
matrix:
  include:
    - jdk: oraclejdk8

script:
  - cd $TRAVIS_BUILD_DIR && cd test && ./runtests.sh # I/O tests
  - cd $TRAVIS_BUILD_DIR && ./gradlew clean test # JUnit tests

addons:
  apt:
    packages:
      - oracle-java8-installer
