language: java
matrix:
  include:
    - jdk: oraclejdk8

install:
  - ./config/travis/download_gradle_wrapper.sh

script:
  - (cd test && ./runtests.sh) # I/O tests
  - ./gradlew -b build.gradle.txt clean test # JUnit tests
  - ./gradlew -b build.gradle.txt asciidoctor # Documentation

deploy:
  skip_cleanup: true
  provider: script
  script: ./config/travis/deploy_github_pages.sh
  on:
    branch: master

addons:
  apt:
    packages:
      - oracle-java8-installer
